# Generated by Django 2.2.4 on 2023-07-26 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wholesaleapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Salesrep',
        ),
    ]
