# Generated by Django 2.2.4 on 2023-07-26 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wholesaleapp', '0002_delete_salesrep'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='company_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='company_phone',
            new_name='phone',
        ),
        migrations.CreateModel(
            name='Salesrep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone_num', models.IntegerField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salesreps', to='wholesaleapp.User')),
            ],
        ),
    ]
