# Generated by Django 2.2.4 on 2023-07-26 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesaleapp', '0003_auto_20230726_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesrep',
            name='phone_num',
            field=models.IntegerField(),
        ),
    ]
