# Generated by Django 2.2.4 on 2023-07-26 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesaleapp', '0004_auto_20230726_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesrep',
            name='phone_num',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
